Repository codeit-internship-group-b/codeit-resources, pull requests merged in 2025-01, with the labels that each got.

#174 [Deploy] PR preview url 생성 workflows 구축
  .github/workflows/preview.yml
Labels: 🌏 Deploy

#175 [Deploy] Revert "[Deploy] Backend Server CI/CD 구축"
  .github/workflows/deploy-cloudfront.yml
  .github/workflows/deploy-express.yml
Labels: 🐞 BugFix

#177 [Deploy] deploy-express.yml ec2 파일 경로수정
  .github/workflows/deploy-cloudfront.yml
  .github/workflows/deploy-express.yml
Labels: 🌏 Deploy, 🐞 BugFix

#158 [Feat] 회의실 예약 api 연동
  apps/web/api/items.ts
  apps/web/api/reservations.ts
  apps/web/app/_hooks/useCurrentTimePosition.ts
  apps/web/app/_hooks/useSlotReservations.ts
  apps/web/app/api/reservation.ts
  apps/web/app/constants/meetingRoomsType.ts
  apps/web/app/constants/reservationConstants.ts
  apps/web/app/constants/reservationFormConstants.ts
  apps/web/app/constants/timeOptions.ts
  apps/web/app/meetings/_components/MeetingRoomSchedule.tsx
  apps/web/app/meetings/_components/Reservation/DesktopReservationSheet.tsx
  apps/web/app/meetings/_components/Reservation/MobileReservationSheet.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm/AttendeesMultiSelect.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm/DeleteButton.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm/NotesInput.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm/RoomDropdown.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm/TimeSelectors.tsx
  apps/web/app/meetings/_components/Reservation/ReservationModal.tsx
  apps/web/app/meetings/_components/Reservation/ReservationSheetContent.tsx
  apps/web/app/meetings/_components/Reservation/ReservationSheets.tsx
  apps/web/app/meetings/_components/Schedule/RoomName.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/CurrentTimeIndicator.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/CurrentTimeLabel.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/ScheduleItem.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/ScheduleSlot.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/ScheduleSlots.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/ScheduleTooltip.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/index.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleTable/ScheduleTableDesktop.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleTable/ScheduleTableMobile.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleTable/index.tsx
  apps/web/app/meetings/_components/main.tsx
  apps/web/app/meetings/_components/skeleton/RoomNameSkeleton.tsx
  apps/web/app/meetings/_components/skeleton/ScheduleSlotSkeleton.tsx
  apps/web/app/meetings/_components/skeleton/TimeTextSkeleton.tsx
  apps/web/app/meetings/_components/skeleton/index.tsx
  apps/web/app/meetings/page.tsx
  apps/web/app/types/ReservationFormTypes.ts
  apps/web/app/types/scheduletypes.ts
  apps/web/app/utils/formatDate.ts
  apps/web/app/utils/timeToMinutes.ts
  apps/web/app/utils/validateTime.ts
  apps/web/components/common/Profile/index.tsx
  apps/web/package.json
  packages/ui/src/components/common/Dropdown/MultiSelectDropdown.tsx
  packages/ui/src/components/common/Dropdown/index.stories.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 🖥 Web, 👾 FE

#179 [Setting] nativewind 세팅 추가
  .expo/README.md
  .expo/devices.json
  apps/mobile/app/(tabs)/index.tsx
  apps/mobile/app/_layout.tsx
  apps/mobile/global.css
  apps/mobile/metro.config.js
  apps/mobile/tailwind.config.js
  apps/mobile/tsconfig.json
  apps/web/components/common/ErrorResetBoundary/index.tsx
  apps/web/components/common/Fallback/index.tsx
Labels: ⚙ Setting, 📱 Mobile

#183 [Fix] FE 배포 오류 해결
  apps/web/app/admin/members/_components/sidepanel/ProfileImageUploader.tsx
  pnpm-lock.yaml
Labels: 🌏 Deploy, 🐞 BugFix

#189 [Refactor] web/src 폴더 제거
  apps/web/app/(seats)/_components/SeatButton.tsx
  apps/web/app/(seats)/_components/SeatGrid.tsx
  apps/web/app/_components/AuthGuard.tsx
  apps/web/app/_hooks/useRediectOnMobile.ts
  apps/web/app/_hooks/useSignInMutation.ts
  apps/web/app/admin/members/_components/ResponsiveMembersPage.tsx
  apps/web/app/admin/members/_hooks/useMembersMutations.ts
  apps/web/app/admin/teams/_components/ResponsiveTeamsPage.tsx
  apps/web/app/admin/teams/_hooks/useTeamsMutations.ts
  apps/web/app/context/SeatContext.tsx
  apps/web/app/dashboard/_components/DashboardProvider.tsx
  apps/web/app/meetings/_components/Reservation/ReservationForm.tsx
  apps/web/app/meetings/_components/Reservation/ReservationSheetContent.tsx
  apps/web/app/meetings/_components/Schedule/ScheduleRow/ScheduleSlot.tsx
  apps/web/app/settings/_components/ResponsiveSettingsPage.tsx
  apps/web/app/settings/_hooks/useUserMutations.ts
  apps/web/app/settings/_hooks/useUserSettingOptions.ts
  apps/web/app/store/useAuthStore.ts
  apps/web/app/utils/notifyMutationError.ts
  apps/web/app/utils/seats.ts
  apps/web/components/Gnb/index.tsx
  apps/web/src/constants/.gitkeep
  apps/web/src/contexts/.gitkeep
  apps/web/src/mocks/.gitkeep
  apps/web/src/types/.gitkeep
Labels: 🔨 Refactor, 👾 FE

#191 [Fix] members 페이지 css 수정 및 teams페이지 에러 수정
  apps/api/src/models/teamModel.ts
  apps/web/app/admin/members/_components/sidepanel/Form.tsx
  apps/web/app/admin/members/_components/sidepanel/Header.tsx
  apps/web/app/admin/members/_components/sidepanel/index.tsx
  apps/web/app/admin/teams/_hooks/useTeamsMutations.ts
  apps/web/app/settings/_components/modals/ManageTeamModal.tsx
Labels: 🐞 BugFix

#162 [Feat] 회의실 관리 페이지
  apps/api/src/controllers/reservationControllers.ts
  apps/web/api/items.ts
  apps/web/api/meetings.ts
  apps/web/app/(admin)/rooms/_components/AddCategoryForm.tsx
  apps/web/app/(admin)/rooms/_components/AddItemButton.tsx
  apps/web/app/(admin)/rooms/_components/CategoryEditDropdown.tsx
  apps/web/app/(admin)/rooms/_components/CategoryList.tsx
  apps/web/app/(admin)/rooms/_components/CategoryListItem.tsx
  apps/web/app/(admin)/rooms/_components/CategoryListSubItem.tsx
  apps/web/app/(admin)/rooms/_components/ConfirmationModal.tsx
  apps/web/app/(admin)/rooms/_components/EditItemForm.tsx
  apps/web/app/(admin)/rooms/_components/ItemsAdminHeader.tsx
  apps/web/app/(admin)/rooms/_components/SidePanel.tsx
  apps/web/app/(admin)/rooms/_store/useMeetingsStore.tsx
  apps/web/app/(admin)/rooms/page.tsx
  apps/web/lib/queryKey.ts
  apps/web/next.config.mjs
  packages/constants/index.ts
  packages/ui/src/components/common/Dropdown/index.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 👾 FE

#195 [Feat] 웹뷰 자동 로그인 구현
  apps/mobile/app/(route)/dashboard.tsx
  apps/mobile/app/(route)/index.tsx
  apps/mobile/app/(route)/meetings.tsx
  apps/mobile/app/(route)/seats.tsx
  apps/mobile/app/(route)/settings.tsx
  apps/mobile/constants/colors.ts
  apps/mobile/hooks/useHandleNavigationActions.ts
  apps/mobile/package.json
  apps/mobile/store/authStorage.ts
  apps/mobile/tsconfig.json
  apps/mobile/utils/getWebViewApiUrl.ts
  apps/mobile/utils/parseMessage.ts
  apps/mobile/utils/sendMessageToWeb.ts
  apps/mobile/utils/webViewLoadHandler.ts
  apps/web/api/auth.ts
  apps/web/api/getWebApiUrl.ts
  apps/web/app/(admin)/members/_components/sidepanel/Header.tsx
  apps/web/app/_components/AuthGuard.tsx
  apps/web/app/_hooks/useAppRouter.ts
  apps/web/app/_hooks/useDetectWebView.ts
  apps/web/app/_hooks/useSignInMutation.ts
  apps/web/app/constants/devices.ts
  apps/web/app/settings/_components/ResponsiveSettingsPage.tsx
  apps/web/app/settings/_components/modals/MembersSettingModal.tsx
  apps/web/app/store/updateWebViewAuthStore.ts
  apps/web/app/store/useAuthStore.ts
  apps/web/app/utils/sendMessageToNative.ts
  apps/web/components/SettingsModal/SettingsModal.tsx
  apps/web/lib/axios.ts
  apps/web/lib/bridge/createWebViewEventListener.ts
  apps/web/lib/bridge/detectWebView.ts
  apps/web/lib/bridge/parseWebViewAuthMessage.ts
  apps/web/lib/bridge/sendMessageToWebView.ts
  packages/constants/index.ts
  packages/ui/src/types/WebViewMessageTypes.ts
  packages/ui/src/utils/storage.ts
  packages/ui/src/utils/stringifyJson.ts
  pnpm-lock.yaml
  turbo.json
Labels: 📱 Mobile
